In [1]:
import numpy as np

In [2]:
# создаем матрицу А
A = np.array([
    [3, 1],
    [2, 2]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [4. 1.]
Собственные векторы: 
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [3]:
# создаем матрицу А
A = np.array([
    [1, -5, -6],
    [4, 8, 7],
    [5, 9, 11]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [13.59373746  5.03209301  1.37416954]
Собственные векторы: 
 [[ 0.45145779  0.83661458  0.10258363]
 [ 0.62348353  0.44632316 -0.77299039]
 [ 0.63832135  0.31760303  0.62606905]]


In [4]:
# Видно, что матрица A будет заведомо вырожденной, так как её третья строка — это результат вычитания первой строки 
# из второй строки. Посмотрим, как поведут себя собственные числа:

# создаем матрицу А
A = np.array([
    [1, -4, -5, -6],
    [4, 12, 8, 7],
    [5, 14, 9, 11],    
    [8, 15, 7, 4]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [ 2.54687092e+01  1.53129080e+00  1.63252001e-14 -1.00000000e+00]
Собственные векторы: 
 [[-0.33176532 -0.6739195   0.5479715  -0.5312532 ]
 [-0.75622544 -0.67703635  0.72006173 -0.64930947]
 [-0.42446012 -0.00311685 -0.00452869 -0.11805627]
 [-0.37133334  0.2957103  -0.42569687  0.5312532 ]]


In [5]:
# Из теоретической части мы знаем, что у данной матрицы собственных чисел нет. Но давайте посмотрим, что по этому 
# поводу думает Python:

# создаем матрицу А
A = np.array([
    [0, 1],
    [-1, 0],
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [0.+1.j 0.-1.j]
Собственные векторы: 
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


In [6]:
# А пока посмотрим на то, как найти спектр корреляционной матрицы на реальной задаче. Возьмём знакомый нам 
# классический датасет о домах в Бостоне. 

from sklearn import datasets 
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# загружаем датасет
boston = datasets.load_boston()
#print(boston['DESCR'])
boston_data = pd.DataFrame(
    data=boston.data, #данные
    columns=boston.feature_names #наименования столбцов
)
boston_data['PRICE']=boston.target
boston_data.head()

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [ ]:
# Составим матрицу наблюдений, в которую войдут все исходные факторы и вектор целевой переменной: 

A = boston_data.drop('PRICE', axis=1)
y = boston_data[['PRICE']]

In [ ]:
# Затем составим корреляционную матрицу для исходных факторов:

C = A.corr()
fig = plt.figure(figsize=(10, 5))
sns.heatmap(C, annot=True, cmap='coolwarm');

In [ ]:
# А теперь найдём собственные числа полученной корреляционной матрицы:

# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(C)
print('Собственные числа: \n', eig_values)
#print('Собственные векторы: \n', eig_vectors)

In [ ]:
# Проверим, что все собственные векторы корреляционной матрицы ортогональны друг другу. Это свойство понадобится нам 
# в методе главных компонент.
# Чтобы это проверить, достаточно найти матрицу Грама , где L — матрица, составленная из собственных факторов. 
# В результате мы должны будем получить единичную матрицу. 
# На её главной диагонали должны быть расположены единицы, а внедиагональные элементы — скалярные произведения 
# собственных векторов — должны быть равны 0. 

# считаем матрицу Грамма L^T*L:
print(np.round(eig_vectors.T @ eig_vectors, 2))

In [10]:
# создаем матрицу А
A = np.array([
    [1, 9, 4],
    [9, 4, 7],
    [4, 7, 12]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A.T@A)
print('Собственные числа: \n', np.round(eig_values))
print('Собственные векторы: \n', np.round(eig_vectors))

Собственные числа: 
 [391.  46.  16.]
Собственные векторы: 
 [[-0. -1. -1.]
 [-1.  1. -0.]
 [-1. -0.  1.]]


In [1]:
# Выберите одну главную компоненту для дальнейшего анализа. Вычислите её значения.
import numpy as np
x1 = np.array([1, 2, 1, 1]).T
x2 = np.array([70, 130, 65, 60]).T

C = np.array([[1, 0.9922], [0.9922, 1]])

eig_values, eig_vectors = np.linalg.eig(C)

x1_norm = (x1 - x1.mean()) / np.linalg.norm(x1)
x2_norm = (x2 - x2.mean()) / np.linalg.norm(x2)

x_new = x1_norm * eig_vectors[0][0] + x2_norm * eig_vectors[1][0]

x_new_norm = (x_new - x_new.mean()) / np.linalg.norm(x_new)

print(np.round(x_new_norm, 2))

[-0.24  0.86 -0.29 -0.33]
