In [29]:
import numpy as np

In [30]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [31]:
A

array([[ 8,  5,  6],
       [ 6, 11,  5],
       [10,  9,  5]])

In [32]:
B

array([[ 1,  2, -2],
       [ 1,  2,  2],
       [ 2,  3,  3]])

In [33]:
# Поэлементное умножение
A*B

array([[  8,  10, -12],
       [  6,  22,  10],
       [ 20,  27,  15]])

In [34]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[25 44 12]
 [27 49 25]
 [29 53 13]]


In [35]:
# Матричное умножение
np.dot(A,B)

array([[25, 44, 12],
       [27, 49, 25],
       [29, 53, 13]])

In [36]:
# Матричное умножение
A@B

array([[25, 44, 12],
       [27, 49, 25],
       [29, 53, 13]])

In [37]:
# Порядок умножения AB != BA
B@A

array([[ 0,  9,  6],
       [40, 45, 26],
       [64, 70, 42]])

In [38]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 5  7 10  7  9]
 [ 9  9  7  8  9]
 [ 9  6  7  7  8]]
B:
 [[-2 -2]
 [-1 -2]
 [ 1  2]
 [ 1 -1]
 [ 0  1]]


In [39]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[  0,  -2],
       [-12, -21],
       [-10, -15]])

In [40]:
# Умножение прямоугольных матриц возможно не в любом порядке
#B@A

In [41]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [42]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 0 -4 -3 -2]
 [ 3 -2 -1 -2]
 [-4  0  3 -3]
 [-2 -3  3  2]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 0 -8  0  2]
 [ 3 -4  0  2]
 [-4  0  0  3]
 [-2 -6  0 -2]]
DA:
 [[ 0 -4 -3 -2]
 [ 6 -4 -2 -4]
 [ 0  0  0  0]
 [ 2  3 -3 -2]]


In [43]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [44]:
#b@A

In [45]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [46]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [47]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [48]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [49]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [52]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
A@x

array([26, 30])

In [53]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [56]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A = np.array([x, y, z])
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [58]:
import pandas as pd
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [63]:
P = Price_DF.values
C = Count_DF.values
salon_inc = (P*C)@com
salon_inc

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [65]:
stylist_inc = (P*C)@(np.ones(5)-com)
stylist_inc

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])